### ISSUE TITLE
Addon breaks on drag

### ISSUE THREAD

**Issue by bagzli** [TheSorm/Raid-Group-Organizer#1]
If I try to drag the Raid Group Organizer window (one where you enter all the names) it basically breaks the addon completely. All the text gets erased and can no longer close the window nor move it and have to reload in order for it to start working again.

**Comment by Road-block** [comment]
[This discussion](https://github.com/Zentarg/BiSTracker/issues/26#issuecomment-866897757) and subsequent fix by BiSTracker author is probably relevant here.

**Comment by TheSorm** [comment]
Should be fixed now
